<div id="content">
    <table>
    <tr><td style="background:#fff;">
    	<img src="images/selfportrait.png" alt="tomas balyo"/>
    </td><td style="background:#fff;">
	<p>
		I am a Post-Doc researcher at <a href="http://algo2.iti.kit.edu/english/index.php">Institute of Theoretical Informatics, Algorithmics II</a> 
		of the <a href="http://www.kit.edu/english/">Karlsruhe Institute of Technology</a> in Karlsruhe, Germany.
	</p>
	<p>
	    I did my Ph.D. at the <a href="http://ktiml.mff.cuni.cz/index.php?lang=english">Department of Theoretical Computer Science and Mathematical Logic</a> 
	    of the <a href="http://www.mff.cuni.cz/toUTF8.en/">Faculty of Mathematics and Physics</a> at the <a href="http://www.cuni.cz/UKENG-1.html">Charles University in Prague</a>
	    under the supervision of <a href="http://ktiml.mff.cuni.cz/~bartak/">Roman Bartak</a> The topic of my doctoral dissertation is <b>Modelling and Solving Problems Using SAT Techniques</b>.
	</p>
	<p>
	    For further information see my <a href="papers/cv_balyo.pdf">CV</a>
	</p>
    </td></tr></table>
    <h3>Contact information</h3>
    <p>
    	<b>Address:</b> see my <a href="http://algo2.iti.kit.edu/english/2403.php">KIT homepage</a><br/>
    	<b>Email:</b> biotomas gmail com<br/>
    </p>
    
</div>
