<div id="content">
    <img src="pictures/wordcloud.svg" width="600" alt="based on words from all my abstracts"/>
    <h3>Research interests</h3>
    <p>
	<ul>
	    <li>
		Boolean Satisfiability Solving (SAT) and friends (#SAT, MAX-SAT, PBO)
	    </li>
	    <li>
		Boolean Function Theory
	    </li>
	    <li>
		Classical A.I. Planning
	    </li>
	    <li>
		Planning as Satisfiability (SATPlan)
	    </li>
	</ul>
    </p>

    <h3>Projects</h3>
    <p>
	<ul>
	    <li>
		<b><a href="https://github.com/biotomas/hordesat">HordeSat</a></b> A massively parallel Satisfiability solver
	    </li>
	    <li>
		<b><a href="https://github.com/biotomas/freelunch">FreeLunch</a></b> An open-soruce Java planning library
	    </li>
	    <li>
		<b><a href="https://github.com/domschrei/aquaplanning">AquaPlanning</a></b> Another open-soruce (educational) Java planning library
	    </li>
	</ul>
    </p>

    <h3>Publications</h3>
    <p>

	<a href="https://scholar.google.de/citations?user=NNVrEbcAAAAJ&hl=en">Google Scholar</a>,
	<a href="https://dblp.uni-trier.de/pers/hd/b/Balyo:Tom=aacute=s">DBLP</a>,
	<a href="http://link.springer.com/search?facet-author=%22Tom%C3%A1%C5%A1+Balyo%22">Springer Link</a>
    </p>
    <p>
	<ul>
	<li><b>2018</b>
	<ol>

    <li>
		Tomas Balyo, Lukas Chrpa:
		<b>Using Algorithm Configuration Tools to Generate Hard SAT Benchmarks</b>,
     SoCS 2018
		<a href = "papers/socs18.pdf">Paper</a>, 
		<a href = "papers/socs18slides.pdf">Slides</a>, 
    </li>

    <li>
		Tomas Balyo, Carsten Sinz:
		<b>Parallel Satisfiability</b>,
    Chapter 1 in Handbook of Parallel Constraint Reasoning, Springer, 2018
    <a href = "https://www.springer.com/de/book/9783319635156">Book</a>, 
    </li>


	</ol>
	</li><li><b>2017</b>
	<ol>

    <li>
		Tomas Balyo, Marijn J. H. Heule, Matti Järvisalo:
		<b>SAT Competition 2016: Recent Developments</b>,
     AAAI 2017
		<a href = "papers/aaai2017.pdf">Paper</a>, 
		<a href = "papers/aaai17slides.pdf">Slides</a>, 
    </li>

    <li>
		Tomas Balyo, Stephan Gocht:
		<b>Accelerating SAT Based Planning with Incremental SAT Solving</b>,
    ICAPS 2017
		<a href = "papers/icaps17.pdf">Paper</a>, 
		<a href = "papers/icaps17slides.pdf">Slides</a>, 
		<a href = "papers/icaps17poster.pdf">Poster</a>
    </li>

    <li>
		Tomas Balyo, Nils Christian Froleyks:
		<b>Using an Algorithm Portfolio to Solve Sokoban</b>,
    SoCS 2017
		<a href = "papers/socs17.pdf">Paper</a>, 
		<a href = "papers/socs17poster.pdf">Poster</a>
    </li>

	    <li>
		Tomas Balyo, Marijn J. H. Heule, and Matti Järvisalo (editors):
		<b>Proceedings of SAT COMPETITION 2017 Solver and Benchmark Descriptions</b>,
    University of Helsinki institutional repository
		<a href = "http://hdl.handle.net/10138/224324">Book</a>, 
		<a href = "https://baldur.iti.kit.edu/sat-competition-2017/">Homepage</a>
	    </li>


	</ol>
	</li><li><b>2016</b>
	<ol>
    <li>
		Tomas Balyo, Martin Suda:
		<b>Reachlunch entering the Unsolvability IPC 2016</b>,
    Unsolvability IPC 2016: planner abstracts, pages 3-6
    <a href = "https://unsolve-ipc.eng.unimelb.edu.au/pdf/planner-summaries.pdf">Paper</a>, 
    </li>

	    <li>
		Tomas Balyo, Marijn J. H. Heule, and Matti Järvisalo (editors):
		<b>Proceedings of SAT COMPETITION 2016 Solver and Benchmark Descriptions</b>,
    University of Helsinki institutional repository
		<a href = "http://hdl.handle.net/10138/164630">Book</a>, 
		<a href = "https://baldur.iti.kit.edu/sat-competition-2016/">Homepage</a>
	    </li>

	    <li>
		Tomas Balyo, Florian Lonsing:
		<b>HordeQBF: A Modular and Massively Parallel QBF Solver</b>,
		19th International Conference on Theory and Applications of Satisfiability Testing
		(SAT) 2016,
		<a href = "papers/sat16.pdf">Paper</a>, 
		<a href = "papers/sat16slides.pdf">Slides</a>, 
		<a href = "http://baldur.iti.kit.edu/hordesat/">Homepage</a>
	    </li>
	</ol>
	</li><li><b>2015</b>
	<ol>
	    <li>
		Tomas Balyo, Peter Sanders, Carsten Sinz:
		<b>HordeSat: A Massively Parallel Portfolio SAT Solver</b>,
		18th International Conference on Theory and Applications of Satisfiability Testing
		(SAT) 2015,
		<a href = "papers/horde.pdf">Paper</a>, 
		<a href = "papers/sat15slides.pdf">Slides</a>, 
		<a href = "http://baldur.iti.kit.edu/hordesat/">Homepage</a>
	    </li>
	    <li>
		Tomas Balyo,  Armin Biere, Markus Iser, Carsten Sinz:
		<b>SAT Race 2015</b>,
		Artificial Intelligence, volume 241
		<a href = "papers/ai15.pdf">Paper</a>, 
		<a href = "https://baldur.iti.kit.edu/sat-race-2015/">Homepage</a>
	    </li>
	    <li>
		Tomas Balyo, Roman Bartak:
		<b>No One SATPlan Encoding To Rule Them All</b>,
		The Eigth Annual Symposium on Combinatorial Search
		(SOCS) 2015,
		<a href = "papers/selective.pdf">Paper</a>, 
		<a href = "papers/socs15-poster.pdf">Poster</a>, 
		<a href = "papers/socs15-slides.pdf">Slides</a>
	    </li>
	</ol>
	</li><li><b>2014</b>
	<ol>
	    <li>
		Tomas Balyo:
		<b>Modelling and Solving Problems Using SAT Techniques</b>,
		PhD thesis, Faculty of Mathematics and Physics, Charles University in Prague, 2014
		<a href = "cas/">thesis website</a>
	    </li>
	    <li>
		Tomas Balyo, Roman Bartak, Otakar Trunda:
		<b>Reinforced Encoding for Planning as SAT</b>,
		Student Conference on Planning in Artificial Intelligence and Robotics
		(PAIR) 2014,
		<a href = "papers/pair14.pdf">Paper</a>, 
		<a href = "papers/pair14slides.pdf">Slides</a>
	    </li>
	    <li>
		Tomas Balyo, Lukas Chrpa, Asma Kilani:
		<b>On Different Strategies for Eliminating Redundant Actions from Plans</b>,
		The Seventh Annual Symposium on Combinatorial Search
		(SOCS) 2014,
		<a href = "papers/socs14.pdf">Paper</a>, 
		<a href = "papers/socsSlides.pdf">Slides</a>
	    </li>
	    <li>
		Tomas Balyo, Andreas Froehlich, Marijn Heule and Armin Biere:
		<b>Everything You Always Wanted to Know About Blocked Sets (But Were Afraid to Ask)</b>,
		17th International Conference on Theory and Applications of Satisfiability Testing
		(SAT) 2014,
		<a href = "papers/sat14.pdf">Paper</a>,
		<a href = "papers/sat14s.pdf">Slides</a>,
		<a href = "bcd/">Resources</a>
	    </li>
	    <li>
		Tomas Balyo, Lukas Chrpa:
		<b>Eliminating All Redundant Actions from Plans Using SAT and MaxSAT</b>, 
		Proceedings of the 5th Workshop  on Knowledge  Engineering  for  Planning  and Scheduling (KEPS) 2014, pp. 16-22,
		Portsmouth, NH, USA, 2014
		<a href = "papers/keps14.pdf">Paper</a>, 
		<a href = "papers/kepsPoster.pdf">Poster</a>,
		<a href = "papers/kepsSlides.pdf">Slides</a>
	    </li>
	</ol>
	<li><b>2013</b>
	<ol>
	    <li>
		Tomas Balyo:
		<b>Relaxing the Relaxed Exist-Step Parallel Planning Semantics</b>, 
		Proceedings of ICTAI 2013, pp 865-871,
		Washington, DC, USA, 2013
		<a href = "papers/ictai13.pdf">Paper</a>, 
		<a href = "papers/ictai13poster.pdf">Poster</a>,
		<a href = "papers/ictai13slides.pdf">Slides</a>
	    </li>
	    <li>
		Martin Babka, Tomas Balyo, Jaroslav Keznikl:
		<b>Solving SMT Problems with a Costly Decision Procedure by Finding Minimum Satisfying Assignments of Boolean Formulas</b>, 
		Studies in Computational Intelligence, volume 496, pp. 231-246, 2013
		<a href = "papers/sera2013.pdf">Paper</a>
	    </li>
	    <li>
		Martin Babka, Tomas Balyo, Jaroslav Keznikl:
		<b>Finding Minimum Satisfying Assignments of Boolean Formulas</b>,
		Poster and abstract in Proceedings of The 26th International FLAIRS Conference 2013, 
		St. Pete Beach, Florida, USA. AAAI, 2013 
		<a href = "https://www.aaai.org/ocs/index.php/FLAIRS/FLAIRS13/paper/download/7207/6156">Abstract Link</a>
	    </li>
	    <li>
		Martin Babka, Tomas Balyo, Ondrej Cepek, Stefan Gurský, Petr Kucera, Václav Vlcek:
		<b>Complexity issues related to propagation completeness</b>, 
		Artificiall Intellingence, volume 206, pp. 19-34, 2013
		<a href = "http://authors.elsevier.com/sd/article/S0004370213000726">Link</a>, 
		<a href = "papers/ai2012.pdf">Paper</a>
	    </li>
	</ol>
	</li><li><b>2012</b>
	<ol>
	    <li>
		Tomas Balyo, Roman Bartak, Pavel Surynek: <b>Shortening Plans by Local Re-Planning</b>, 
		Proceedings of ICTAI 2012, 
		Athens, Greece, 2012
		<a href = "papers/ictai2012.pdf">Paper</a>
	    </li>
	    <li>
		Tomas Balyo, Roman Bartak, Pavel Surynek: <b>On Improving Plan Quality via Local Enhancements</b>, 
		Proceedings of SOCS 2012, 
		Niagara Falls, Ontario, Canada, 2012 (short paper)
		<a href = "papers/socs2012.pdf">Paper</a>
		<a href = "papers/socs2012-poster.pdf">Poster</a>
	    </li>
	    <li>
		Tomas Balyo, Stefan Gursky, Petr Kucera, Vaclav Vlcek: <b>On Hierarchies over the SLUR Class<sup>1</sup></b>, 
		Proceedings of ISAIM 2012, 
		Fort Lauderdale, Florida, USA, 2012
		<a href = "papers/isaim2012.pdf">Paper</a>
	    </li>
	</ol>
	</li><li><b>2011 - 2009</b>
	<ol>
	    <li>
		Tomas Balyo, Dan Toropila, Roman Bartak: <b>Two Semantics for Step-Parallel Planning: Which One to Choose?<sup>1</sup></b>, 
		Proceedings of PLANSIG 2011, 
		Huddersfield, United Kingdom, 2011 
		<a href = "papers/plansig2011.pdf">Paper</a>
	    </li>
	    <li>
		Tomas Balyo: <b>Decomposing Boolean formulas into connected components</b>,
		Proceedings of the 20th Annual Conference of Doctoral Students - WDS 2011, 
		Prague, Czech Republic, 2011
		<a href = "papers/wds2011.pdf">Paper</a>
	    </li>
	    <li>
		Tomas Balyo: <b>Solving Boolean satisfiability problems</b>, Master thesis, Faculty of Mathematics and 
		Physics, Charles University in Prague, 2010
		<a href = "papers/master.pdf">Thesis</a>
	    </li>
	    <li>
		Tomas Balyo, Pavel Surynek: <b>Efektivni heuristika pro SAT zalozena znalosti 
		komponent souvislosti grafu problemu (An Efficient Heuristic for SAT Exploiting 
		Connected Components of the Problem)</b> Proceedings of the Conference Znalosti 2009, 
		Brno, Czech Republic, 2009 
		<a href = "papers/znalosti2009.pdf">Paper</a>
	    </li>
	</ol>
	</li>
    </ul>
    </p>
    <hr/>
    <sup>1</sup> Also presented on the 14th Czech-Japan Seminar on Data Analysis and Decision Making 2011.
</div>
