<div class="sidebar">
    <ul>	
       <li>
            <h4>Navigate</h4>
            <ul class="blocklist">
            	<?php include("menu.phtml"); ?>
            </ul>
        </li>
        <li>
            <h4>Quicklinks</h4>
            <ul>
                <li><a href="https://github.com/biotomas/freelunch"><strong>FreeLunch</strong></a> Open-source planner and planning library</li>
                <li><a href="https://github.com/biotomas"><strong>GitHub</strong></a> My professional/hobby software projects</li>
            </ul>
        </li>
    </ul>
</div>
