<div id="content">
<p> </p>
    <h3>AUTOMATED PLANNING AND SCHEDULING</h3>
    <p>
	A lecture at KIT with <a href="https://www.dominikschreiber.de/">Dominik Schreiber</a> on practically orientend automated (Artificial Intelligence) planning and scheduling.
	<a href="https://algo2.iti.kit.edu/balyo/plan/">Lecture Homepage</a>. 
    </p>

    <h3>PRACTICAL SAT SOLVING</h3>
	A lecture at KIT with <a href="http://www.carstensinz.de/">Carsten Sinz</a> on practically orientend Boolean Satisfiability (SAT) solving.
	<a href="https://baldur.iti.kit.edu/sat/">Lecture Homepage</a>. 
    <p>
    </p>
  </div>
